name = "fauna-workers"
type = "javascript"

account_id = ""
workers_dev = true
route = ""
zone_id = ""
compatibility_date = "2022-02-02"

[build]
command = "npm run build"

[build.upload]
format = "service-worker"

kv_namespaces = [ 
  { binding = "DOG_KV", id = "8e9ce64cec994e4e8ffca41143dbc23c" }
]